### ISSUE TITLE
escape sequence at beginning of output

### ISSUE THREAD

**Issue by JPT77** [MrShoenel/mkvinfo2json#3]
at the beginning of the output you add `[32m` to make the font look green.
I used > to pipe the output into a file
Yeah, I know there is the -o option which does not add any chars to the output.

Other software detects if it is writing to console or into file...
since the output is not pretty printed, why bother coloring it?

thank you very much

**Comment by MrShoenel** [comment]
I am not sure this should be fixed (not an error in my opinion), since `-o` exists. Also, when writing to console, the code can be beautified (the intended behavior when you do not need to write to file).
So, unless you have another strong reason for changing this, I would rather keep it this way :)

**Comment by JPT77** [comment]
Fine, let's close this.
